### ISSUE TITLE
Numbers for listed patch files are on the wrong line, missing line feed

### ISSUE THREAD

**Issue by MeetYouAt305** [MarisElsins/getMOSPatch#10] opened 2017-10-27 09:06 UTC
```
Processing patch 22384200 for Czech (CS) and applying regexp .* to the filenames:                                                                                                        1 - p22384200_R12.AP.B_R12_cs.zip
 Enter Comma separated files to download: 1

```

**Comment by MarisElsins** [comment] 2017-10-27 14:01
Thanks for reporting this, could you provide the exact command you executed to initiate the patch download please?

**Comment by MeetYouAt305** [comment] 2017-10-28 10:30
Hi Maris,

I used:
java -jar getMOSPatch.jar MOSUser=chad.smith@eu.panasonic.com
patch=22384200 download=all

Then I entered the platform (SPARC Solaris 64-bit) and the languages (IT,
FR, ES, NL, CZ).

Chad

Maris Elsins <notifications@github.com> schrieb am Fr. 27. Okt. 2017 um
16:03:

**Comment by MarisElsins** [comment] 2017-10-30 13:33
Hi Chad,

Sorry, I was not able to reproduce this - https://pastebin.com/S4VYH6YF
You could try running it with "silent=yes" argument which disables the cursor animation (which probably is the issue there)

**Comment by MarisElsins** [comment] 2018-01-23 07:49
Couldn't reproduce. Closing it.

**Closed by MarisElsins** 2018-01-23 07:49 UTC
