### ISSUE TITLE
Platform or language is changed.

### ISSUE THREAD

**Issue by Pafke01** [MarisElsins/getMOSPatch#27] opened 2021-04-21 08:27 UTC
Downloading is not working anymore because there is a problem with the platforms definition.

PS D:\OpatchDownload> .\haalop3.ps1
 Downloading patch:  Patch 32579074: COMBO OF OJVM COMPONENT 12.1.0.2.210420 DB PSU + DBPSU 12.1.0.2.210420
32579074                                                                                                              Platforms and languages need to be reset.
Obtaining the list of platforms and languages:                                                                         -
Enter Comma separated platforms to list: 111
 ERROR: Unparsable inputs. Try Again.
Enter Comma separated platforms to list:226P - Linux x86-64

Result in download issues:

-
We're going to download patches for the following Platforms/Languages:
 209P - IBM: Linux on System z
 2000P - Generic Platform
 233P - Microsoft Windows x64 (64-bit)
 226P - Linux x86-64

Processing patch 32579074 for IBM: Linux on System z and applying regexp .* to the filenames:
-\ No files available

Processing patch 32579074 for Generic Platform and applying regexp .* to the filenames:
-\ No files available

Processing patch 32579074 for Microsoft Windows x64 (64-bit) and applying regexp .* to the filenames:
-\ No files available

Processing patch 32579074 for Linux x86-64 and applying regexp .* to the filenames:
-\ No files available

There's Nothing to download!

I am not that good in java and eclipse.....could you please have a look ?

Regards,
Paul

**Comment by MarisElsins** [comment] 2021-04-21 09:00
Hi Paul,

The DB 12.1 patches require Extended Support access configured for the CSI you're using.
The simplest way to check that you have it is to connect to the MOS and check if the download for these patches is available for you there. The getMOSPatch shows "No files available" when the patch download is not available (i.e. due to insufficient access), so I assume this is going to be the case here.

Please, let me know if it's not.

Maris

**Comment by Pafke01** [comment] 2021-04-21 09:07
It is is not a csi issue...all versions are affected:

I am able to download them manually from :
https://updates.oracle.com/Orion/SimpleSearch/process_form?search_type=patch&patch_number=32579074&plat_lang=226P&display_type=&search_style=8&orderby=&direction=&old_type_list=&gobuttonpressed=&sortcolpressed=&tab_number=&email=paulfrans.musolf%40centric.eu&userid=o-paulfrans.musolf%40centric.eu&c_release_parent=product&c_product_child=release

The platform list is not populated as shown in my previous post.

Regards,
Paul

**Comment by MarisElsins** [comment] 2021-04-21 09:19
OK, something's broken indeed. I've got the "unparsable inputs" too.
But I used this as a workaround and It appears to have worked. Does this help you?

```
$ java -jar getMOSPatch.jar patch=32579074 platform=209P,2000P,233P,226P
...
-
We're going to download patches for the following Platforms/Languages:
 209P - Platform 209P
 2000P - Platform 2000P
 233P - Platform 233P
 226P - Platform 226P

Processing patch 32579074 for Platform 209P and applying regexp .* to the filenames:
 1 - p32579074_121020_Linux-zSer.zip
 Enter Comma separated files to download ("all" or "none" can be used too): none

Processing patch 32579074 for Platform 2000P and applying regexp .* to the filenames:
 No files available

Processing patch 32579074 for Platform 233P and applying regexp .* to the filenames:
 No files available

Processing patch 32579074 for Platform 226P and applying regexp .* to the filenames:
 1 - p32579074_121020_Linux-x86-64.zip
 Enter Comma separated files to download ("all" or "none" can be used too): none

There's nothing to download!
```

**Comment by Pafke01** [comment] 2021-04-21 09:26
Unfortunately:
 Downloading patch:  Patch 32579074: COMBO OF OJVM COMPONENT 12.1.0.2.210420 DB PSU + DBPSU 12.1.0.2.210420
32579074                                                                                                               -
We're going to download patches for the following Platforms/Languages:
 209P - Platform 209P
 226P - Platform 226P

Processing patch 32579074 for Platform 209P and applying regexp .* to the filenames:                                   No files available

Processing patch 32579074 for Platform 226P and applying regexp .* to the filenames:                                   No files available

There's Nothing to download!


Regards,
Paul

**Comment by MarisElsins** [comment] 2021-04-21 09:34
I see, I'll need more time to figure it out.

**Comment by Pafke01** [comment] 2021-04-21 10:03
No problem... I am able to download manualy.
Regards,

Paul

**Comment by neosonic2** [comment] 2023-05-19 18:22
Has there been any progress made with regards to resolving this issue? I wanted to use this solution to download the latest Java JDK and JRE RPM packages, but when I try to do so with this command (credentials removed on purpose):

java -jar getMOSPatch.jar patch=18143322,13079846 MOSUser=<USERNAME> MOSPass=<PASSWORD> platform=226P download=all stagedir="/tmp/javadl"

I get the following error, exactly as what others have seen here:

Enter Comma separated platforms to list: 226P
 ERROR: Unparsable inputs. Try Again.
 
 I am running Linux x64 which does correctly correspond to platform 226P so I'm not quite sure what the problem is here. I have also checked that the MOS credentials I supplied are correct, and I can download the latest RPMs from the two mentioned patches (18143322 and 13079846) manually without issue.

**Comment by MarisElsins** [comment] 2024-04-24 21:08
I tried reproducing it again, it worked. Also this is 3y old issue, I'll just close it.
```
$ java -jar getMOSPatch.jar patch=18143322,13079846 platform=226P download=all
Enter your MOS username: 
Enter your MOS password: 
|
We're going to download patches for the following Platforms/Languages:
 226P - Platform 226P

Processing patch 18143322 for Platform 226P and applying regexp .* to the filenames:
 1 - p18143322_1800_Linux-x86-64.zip
 Enter Comma separated files to download: all
 All files will be downloaded because download=all was specified.

Processing patch 13079846 for Platform 226P and applying regexp .* to the filenames:
 1 - p13079846_17000_Linux-x86-64.zip
 Enter Comma separated files to download: all
 All files will be downloaded because download=all was specified.

Downloading all selected files:
 Downloading p18143322_1800_Linux-x86-64.zip: 535MB at average speed of 17138KB/s - DONE!  
 Downloading p13079846_17000_Linux-x86-64.zip: 256MB at average speed of 3318KB/s - DONE!  
```

**Closed by MarisElsins** 2024-04-24 21:08 UTC
